language: python
python:
  - "2.7"
  - "3.3"
  - "pypy"
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsmokeqt4-dev xvfb
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - pip install -r requirements.txt
  - cmake .
  - make
  - pip install .
# command to run tests
script:
  - # Segfaults with pypy if jit is enabled
  - if [ "$TRAVIS_PYTHON_VERSION" = "pypy" ]; then python --jit off -m nose ; else nosetests; fi
